'use client';
import {useCallback,useEffect,useRef,useState} from 'react';

const moves=[
 ['Jumping jacks','Ouvre et ferme bras et jambes en rythme.','0% 0%'],['Chaise au mur','Dos plaqué, cuisses parallèles au sol.','33.33% 0%'],['Pompes','Corps gainé, poitrine vers le sol.','66.66% 0%'],['Abdominaux','Décolle les épaules sans tirer la nuque.','100% 0%'],['Step-up chaise','Pousse dans le talon, alterne les jambes.','0% 50%'],['Squats','Hanches en arrière, genoux dans l’axe.','33.33% 50%'],['Dips sur chaise','Coudes vers l’arrière, épaules basses.','66.66% 50%'],['Planche','Serre les abdos et garde le dos droit.','100% 50%'],['Montées de genoux','Reste léger et monte les genoux.','0% 100%'],['Fentes','Descends verticalement, alterne les côtés.','33.33% 100%'],['Pompes en T','Tourne le buste et tends le bras.','66.66% 100%'],['Planche latérale','Hanches hautes, corps bien aligné.','100% 100%'],
] as const;
type Phase='ready'|'work'|'rest'|'done';

export default function Home(){
 const[idx,setIdx]=useState(0),[phase,setPhase]=useState<Phase>('ready'),[sec,setSec]=useState(30),[running,setRunning]=useState(false),[soundReady,setSoundReady]=useState(false),[music,setMusic]=useState(true);
 const end=useRef(0),lock=useRef(false),warned=useRef(false),audio=useRef<AudioContext|null>(null);
 const beep=useCallback((f=720,d=.1)=>{const c=audio.current;if(!c)return;const o=c.createOscillator(),g=c.createGain();o.frequency.value=f;o.type='sine';g.gain.setValueAtTime(.0001,c.currentTime);g.gain.exponentialRampToValueAtTime(.16,c.currentTime+.01);g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+d);o.connect(g).connect(c.destination);o.start();o.stop(c.currentTime+d)},[]);
 const say=useCallback((text:string,energy=true)=>{beep(energy?780:520);if('speechSynthesis'in window){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text),vs=speechSynthesis.getVoices();u.voice=vs.find(v=>v.lang==='fr-FR'&&/Denise|Henri|Google|Natural|Online/i.test(v.name))||vs.find(v=>v.lang.startsWith('fr'))||null;u.lang='fr-FR';u.rate=energy?1.08:.96;u.pitch=energy?1.05:1;speechSynthesis.speak(u)}},[beep]);
 const advance=useCallback(()=>{if(lock.current)return;lock.current=true;if(phase==='work'){setPhase('rest');setSec(15);end.current=Date.now()+15000;warned.current=false;say('Récupération. Quinze secondes.',false)}else if(idx<11){const n=idx+1;setIdx(n);setPhase('work');setSec(30);end.current=Date.now()+30000;warned.current=false;say(`${moves[n][0]}. C’est parti !`)}else{setPhase('done');setSec(0);setRunning(false);say('Session terminée. Solide !')}setTimeout(()=>lock.current=false,300)},[idx,phase,say]);
 useEffect(()=>{if(!running||phase==='ready'||phase==='done')return;const t=setInterval(()=>{const n=Math.max(0,Math.ceil((end.current-Date.now())/1000));setSec(n);if(phase==='work'&&n===5&&!warned.current){warned.current=true;say('Cinq secondes. Ne lâche rien !')}if(n===0)advance()},200);return()=>clearInterval(t)},[running,phase,advance,say]);
 const start=async()=>{audio.current=new AudioContext();await audio.current.resume();speechSynthesis?.resume();setSoundReady(true);setIdx(0);setPhase('work');setSec(30);end.current=Date.now()+30000;setRunning(true);say('NEUFMIN démarre. Jumping jacks !')};
 const toggle=()=>{if(phase==='done'){start();return}if(running){setSec(Math.max(0,Math.ceil((end.current-Date.now())/1000)));setRunning(false)}else{end.current=Date.now()+sec*1000;setRunning(true)}};
 const jump=(n:number)=>{if(n<0||n>11)return;setIdx(n);setPhase('work');setSec(30);warned.current=false;if(running)end.current=Date.now()+30000;say(moves[n][0])};
 const phaseTotal=phase==='rest'?15:30,arc=Math.max(0,Math.min(100,(sec/phaseTotal)*100));
 const elapsed=phase==='done'?540:idx*45+(phase==='rest'?30+(15-sec):phase==='work'?30-sec:0),overall=Math.min(100,elapsed/540*100);
 const nextIdx=Math.min(11,idx+1);
 return <main className={`app ${phase}`}>
  {!soundReady&&<section className="launch"><div className="launchMark">NM</div><div className="launchCopy"><span>SESSION GUIDÉE · 09:00</span><h1>TON CORPS.<br/><em>TON ROUND.</em></h1><p>12 mouvements. 30 secondes d’effort. 15 secondes pour reprendre ton souffle. Un clic, puis on pilote tout.</p><button onClick={start}>DÉMARRER AVEC LE SON <b>↗</b></button></div><div className="launchStats"><div><b>12</b><span>EXERCICES</span></div><div><b>30</b><span>SEC ON</span></div><div><b>15</b><span>SEC OFF</span></div></div></section>}
  <header className="topbar"><div className="wordmark"><i/>NEUF<span>MIN</span></div><div className="total"><span>PROGRESSION</span><div><i style={{width:`${overall}%`}}/></div><b>{Math.round(overall)}%</b></div><div className="topActions"><button onClick={()=>setMusic(v=>!v)}>{music?'♫ ON':'♫ OFF'}</button><span>{String(idx+1).padStart(2,'0')} / 12</span></div></header>
  <section className="dashboard">
   <aside className="brief"><div className="live"><i/>{phase==='rest'?'RÉCUPÉRATION':phase==='done'?'TERMINÉ':'EN COURS'}</div><span className="number">{String(idx+1).padStart(2,'0')}</span><h2>{phase==='rest'?'RESPIRE':phase==='done'?'SOLIDE !':moves[idx][0]}</h2><p>{phase==='rest'?`Prochain mouvement : ${moves[nextIdx][0]}`:phase==='done'?'Tu viens de terminer les 12 mouvements.':moves[idx][1]}</p><div className="next"><small>ENSUITE</small><b>{idx<11?moves[nextIdx][0]:'FIN DU ROUND'}</b><span>{idx<11?'30 SEC':'BRAVO'}</span></div><div className="protocol"><span><b>30</b> TRAVAIL</span><i/><span><b>15</b> REPOS</span></div></aside>
   <div className="motion"><div className="figure" key={idx} style={{backgroundPosition:moves[idx][2]}}/><button className="prev" onClick={()=>jump(idx-1)} disabled={idx===0}>←</button><button className="nextBtn" onClick={()=>jump(idx+1)} disabled={idx===11}>→</button><div className="motionLabel"><span>DÉMONSTRATION</span><b>{moves[idx][0]}</b></div></div>
   <aside className="timer"><div className="phaseLabel"><i/>{phase==='rest'?'REPOS':phase==='done'?'FINISH':'EFFORT'}</div><div className="dial" style={{background:`conic-gradient(${phase==='rest'?'var(--lime)':'var(--orange)'} ${arc*3.6}deg,#292b26 0)`}}><div><b>{String(sec).padStart(2,'0')}</b><span>SECONDES</span></div></div><button className="pause" onClick={toggle}>{running?'Ⅱ  PAUSE':'▶  REPRENDRE'}</button><small>TOUT S’ENCHAÎNE AUTOMATIQUEMENT</small></aside>
  </section>
  <section className="rail">{moves.map((m,i)=><button key={m[0]} className={i===idx?'active':i<idx?'past':''} onClick={()=>jump(i)}><span>{String(i+1).padStart(2,'0')}</span><div className="thumb" style={{backgroundPosition:m[2]}}/><b>{m[0]}</b></button>)}</section>
  {soundReady&&music&&<div className="music"><iframe src="https://www.youtube.com/embed/3ArOBAt5Ml0?autoplay=1&start=16&loop=1&playlist=3ArOBAt5Ml0&controls=0&playsinline=1&rel=0" title="Musique d’entraînement" allow="autoplay; encrypted-media"/><span><i/> LIVE MUSIC</span></div>}
 </main>
}
